name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: TestDB
      run: |
        echo "check psql"
        postgres --version
      shell: bash

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
